### ISSUE TITLE
Unzip error

### ISSUE THREAD

**Issue by AdamNZ** [Externoak/A32NX-installer#3]
I get an unzip error when I point it to my Community folder. Works great if I point it to any other temporary location ... then I simply copy/replace.

I suspect the error is because the Community folder is protected (it's an MS Store install). More likely, though, the culprit is the stupidly long folder name MS Store creates by default.

**Comment by Externoak** [comment]
Thanks for the feedback. 
Yes, a few people have reported back the same issue. It seems to be a protected directory. I will add a check and inform if this is the case.

**Comment by AdamNZ** [comment]
Thanks - and thanks for this handy little utility!!!

**Comment by Externoak** [comment]
@AdamNZ Should now be fixed in commit https://github.com/Externoak/A32NX-installer/commit/4b0f6ed49bf1bd54a69aa6ac3cb3cc2d0f2c721d

**Comment by Externoak** [comment]
https://github.com/Externoak/A32NX-installer/releases/tag/v0.3 Fixes this issue.

**Comment by DennisK312** [comment]
I still get an error while installing. Folder could not be unzipped, failed reason: FileNotFoundError(2, No such file or directory')!
I have already moved the installer to a different location and the destination folder to a different place but no succes.
What else can i do to have the installer to work?
